### ISSUE TITLE
Get DRM License URL

### ISSUE THREAD

**Issue by kavitamp** [halilozel1903/ExoPlayerDrm#1]
Hi @halilozel1903

The code sample for playing DRM content was very helpful, thank you for sharing it with us.
I need help to understand from where did you get the DRM license URL?
In my application, I am using Azure Media Service & Widevine DRM.

**Comment by halilozel1903** [comment]
Hello,

Unfortunately, I have no information other than the example.

**Comment by kavitamp** [comment]
Alright, Thank you @halilozel1903
